export const sampleSegments = [
  {
    id: "101",
    speakerLabel: "Host",
    speakerTheme: "host",
    timecode: "00:00:00",
    text: "Welcome to WhisperScript! We're excited to show you how fast editing can be.",
    metrics: { cps: 12, wpm: 142, words: 12, seconds: 4 },
    showBadge: true,
    selected: true,
    showTimecode: true,
    waveStart: 0,
    waveEnd: 0.18,
  },
  {
    id: "102",
    speakerLabel: "Host",
    speakerTheme: "host",
    timecode: "00:00:02",
    text: "This sample transcript demonstrates the toolbar actions and speaker colors.",
    metrics: { cps: 10, wpm: 128, words: 11, seconds: 5 },
    waveStart: 0.18,
    waveEnd: 0.38,
  },
  {
    id: "103",
    speakerLabel: "Guest",
    speakerTheme: "guest",
    timecode: "00:00:04",
    text: "You can edit segments, adjust timing, and export polished transcripts in seconds.",
    metrics: { cps: 14, wpm: 166, words: 13, seconds: 5 },
    showBadge: true,
    waveStart: 0.38,
    waveEnd: 0.61,
  },
  {
    id: "104",
    speakerLabel: "Host",
    speakerTheme: "host",
    timecode: "00:00:07",
    text: "Need multiple speakers? Color-coded badges keep every voice organized.",
    metrics: { cps: 11, wpm: 140, words: 10, seconds: 4 },
    showBadge: true,
    waveStart: 0.61,
    waveEnd: 0.82,
  },
  {
    id: "105",
    speakerLabel: "Narrator",
    speakerTheme: "narrator",
    timecode: "00:00:09",
    text: "Try clicking different rows in the real app to see search, metrics, and inline layouts.",
    metrics: { cps: 9, wpm: 120, words: 14, seconds: 7 },
    showBadge: true,
    waveStart: 0.82,
    waveEnd: 1,
  },
];
